__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [4]:
import numpy as np
import scipy
from scipy.linalg import lu

In [20]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

In [21]:
def solve_LU(A, b):
    P, L, U = scipy.linalg.lu(A)
    y = np.dot(np.linalg.inv(L), b)
    x = np.dot(np.linalg.inv(U), y)
    return x


x = solve_LU(A, b)
x

array([ 3.38461538, -3.11538462, -2.88461538])

In [22]:
# проверка A * x = b
np.dot(A, x)

array([-5.,  1., -6.])

Вопрос преподавателю: 

1)верно ли решение, учитывая, что порядок чисел в векторе b после проверки и в заданном векторе b отличается? 

2)ниже я решила без разложения и ответы совпали с теми, что я решила на листике, делая разложение, а при проверке порядок чисел в векторе b правильный.

In [23]:
z = np.linalg.solve(A, b)
z

array([-1.,  0.,  1.])

In [24]:
np.dot(A, z)

array([ 1., -6., -5.])