# Часть 1
__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
       
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

In [4]:
import numpy as np

a)

In [5]:
A = np.zeros((4, 2))
B = np.zeros((4, 2))
C = A.dot(B)
C

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

In [6]:
D = B.dot(A)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

б)

In [7]:
A = np.zeros((2, 5))
B = np.zeros((5, 3))
C = A.dot(B)
C

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
D = B.dot(A)
D

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

в)

In [9]:
A = np.zeros((8, 3))
B = np.zeros((3, 8))
C = A.dot(B)
D = B.dot(A)
C, D

(array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

г)

In [10]:
A = np.zeros((4, 4))
B = np.zeros((4, 4))
C = A.dot(B)
D = B.dot(A)
C, D

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [11]:
A = np.matrix([[1, -2], [3, 0]])
B = np.array ([[4, -1], [0, 5]])
A, B

(matrix([[ 1, -2],
         [ 3,  0]]),
 array([[ 4, -1],
        [ 0,  5]]))

In [12]:
C = np.add(A, B)
D = np.dot(A, B)
C, D

(matrix([[ 5, -3],
         [ 3,  5]]),
 matrix([[  4, -11],
         [ 12,  -3]]))

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [13]:
A = np.matrix([[1, 7], [3, -6]])
B = np.matrix([[0, 5], [2, -1]])
C = np.matrix([[2, -4], [1, 1]])

D = 3 * A - 2 * B + 4 * C
D

matrix([[ 11,  -5],
        [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

In [14]:
A = np.matrix([[4, 1], [5, -2], [2, 3]])
B = A.dot(A.T)
C = np.dot(A.T, A)
B, C

(matrix([[17, 18, 11],
         [18, 29,  4],
         [11,  4, 13]]),
 matrix([[45,  0],
         [ 0, 14]]))

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [100]:
def matrix_multiplication(A, B):
    if len(A[0]) != len(B):
        return ('Матрицы невозможно перемножить (не удовлетворено условие "число столбцов первой матрицы = числу строк второй матрицы")')
    else:
        return [[sum(elem_A * elem_B for elem_A, elem_B in zip(row_A, col_B)) for col_B in list(zip(*B))] for row_A in A]


X = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
Y = [[1,2],[1,2],[3,4]]

A = [[1, 7], [3, -6]]
B =  [[0, 5], [2, -1]]

E = np.zeros((4, 2))
F = np.zeros((4, 2))
    
print(f'X * Y: {matrix_multiplication(X, Y)}')
print(f'A * B: {matrix_multiplication(A, B)}')
print(f'E * F: {matrix_multiplication(E, F)}')

X * Y: [[12, 18], [27, 42], [42, 66], [57, 90]]
A * B: [[14, -2], [-12, 21]]
E * F: Матрицы невозможно перемножить (не удовлетворено условие "число столбцов первой матрицы = числу строк второй матрицы")


# Часть 2
__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

 

In [121]:
x = int(np.random.sample(1))

A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])

print(np.linalg.det(A))

1.0


  б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [123]:
A = np.array([[4, 2, 3 ], [0, 5, 1], [0, 0, 9]])
print(np.linalg.det(A))

180.0


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

In [126]:
A = np.array([[1, 2, 3 ], [4, 5, 6], [7, 8, 9]])
print(round(np.linalg.det(A)))

0


__2.__  В тетради

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [129]:
A = np.matrix([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [132]:
A = np.matrix([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(np.linalg.matrix_rank(A))

2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [134]:
B = np.matrix([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(np.linalg.matrix_rank(B))

3
