1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [2]:
import numpy as np

In [3]:
A = np.matrix([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
U, s, W = np.linalg.svd(A)

In [5]:
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [6]:
A

matrix([[ 1,  2,  0],
        [ 0,  0,  5],
        [ 3, -4,  2],
        [ 1,  6,  5],
        [ 0,  1,  0]])

In [7]:
U

matrix([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
        [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
        [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
        [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
        [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [8]:
D

matrix([[8.82486885, 0.        , 0.        ],
        [0.        , 6.14060608, 0.        ],
        [0.        , 0.        , 2.53271528],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]])

In [9]:
V

matrix([[ 0.07116451, -0.36737824, -0.92734505],
        [ 0.71702467,  0.66514082, -0.20847855],
        [ 0.69340553, -0.65009301,  0.31075368]])

In [13]:
# проверка
np.dot(np.dot(U, D), V.T)

matrix([[ 1.00000000e+00,  2.00000000e+00, -1.72084569e-15],
        [-6.66133815e-16,  6.66133815e-16,  5.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
        [ 1.00000000e+00,  6.00000000e+00,  5.00000000e+00],
        [ 5.55111512e-17,  1.00000000e+00,  0.00000000e+00]])


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [18]:
# евклидова норма равна наибольшему сингулярному числу(мю1)
s[0] 

8.824868854820448

In [19]:
# второй способ найти евклидову норму
np.linalg.norm(A, ord=2)

8.824868854820442

In [20]:
# норма Фробениуса
np.linalg.norm(A)

11.045361017187261